# Generated by Django 3.1.5 on 2021-01-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='f_axle',
            field=models.IntegerField(choices=[(1, 'QR'), (2, 'Thru'), (3, 'Other')], default=3),
        ),
        migrations.AddField(
            model_name='bike',
            name='r_axle',
            field=models.IntegerField(choices=[(1, 'QR'), (2, 'Thru'), (3, 'Other')], default=3),
        ),
        migrations.AlterField(
            model_name='bike',
            name='type',
            field=models.IntegerField(choices=[(1, 'Road'), (2, 'Mountain'), (3, 'Hybrid'), (4, 'Comfort/Cruiser'), (5, 'E-Bike'), (6, 'Other')]),
        ),
    ]
