# Generated by Django 3.1.5 on 2021-01-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_auto_20210121_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='brake_type',
            field=models.IntegerField(choices=[(1, 'Disc'), (2, 'Rim')], default=1),
        ),
    ]
