# Generated by Django 3.1.5 on 2021-01-21 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericWheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoke_count', models.PositiveIntegerField(blank=True, default=32, null=True)),
                ('manufacturer', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('is_disc', models.BooleanField(blank=True, default=True, null=True)),
                ('tubeless', models.BooleanField(blank=True, default=True, null=True)),
                ('axle', models.IntegerField(choices=[(1, 'QR'), (2, 'Thru'), (3, 'Other')], default=3)),
                ('material', models.IntegerField(blank=True, choices=[(1, 'Carbon'), (2, 'Alloy'), (3, 'Other')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontWheel',
            fields=[
                ('genericwheel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wheel.genericwheel')),
            ],
            bases=('wheel.genericwheel',),
        ),
        migrations.CreateModel(
            name='RearWheel',
            fields=[
                ('genericwheel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wheel.genericwheel')),
                ('driver', models.IntegerField(choices=[(1, 'Shimano/SRAM 11s'), (2, 'XD'), (3, 'XDR'), (4, 'Shimano Micro Spline'), (5, 'Campagnolo')])),
                ('single_speed_only', models.BooleanField()),
                ('fixed', models.BooleanField()),
            ],
            bases=('wheel.genericwheel',),
        ),
    ]
