# Generated by Django 3.1.5 on 2021-01-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rearwheel',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rearwheel',
            name='single_speed_only',
            field=models.BooleanField(default=False),
        ),
    ]
