# Generated by Django 3.1.5 on 2021-01-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0002_auto_20210120_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rearwheel',
            name='driver',
            field=models.IntegerField(choices=[(1, 'Shimano/SRAM 11s'), (2, 'XD'), (3, 'XDR'), (4, 'Shimano Micro Spline'), (5, 'Campagnolo'), (6, 'Other')]),
        ),
    ]
